### ISSUE TITLE
As a user I want to search across all pages by keyword so I can find specific content that interests me.

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/cdh-web#19]
# dev notes

- [x] create separate branch to track #359 and remove/reset code related to it from this branch
- [x] add tests for `SiteSearchView`
- [x] implement search result styles from #364 
- [x] implement search bar styles from #367
- [x] add new snapshots/states to percy for visual testing of search

**Comment by cvansant** [comment]
I searched for myself (https://test-web.cdh.princeton.edu/search/?q=camey&page=1)and here's what I found:

- For the most part, the order in which the search results come up makes sense: 1) my staff profile; 2) blog posts in which I am mentioned;  3) blog posts I authored; 4) other pages that mention me. The main question I have relates to 4). I think perhaps pages that mention me should come before the blog posts I authored. For instance, if I were really searching for me, I would want to see that I was listed on the S&Co project page. There certainly could be other views on this, however.
- most of the pages associated with my name say "last updated: April 21, 2021." Perhaps that was the day of the migration? it is not true that most of them were updated then.
- The blog posts are in chronological order, with the earliest ones listed first. I think it would make more sense if the more recent ones were listed first. I don't know what if anything this has to do with the April 21 situation.

I searched for "charter" (https://test-web.cdh.princeton.edu/search/?q=charter&page=1)
- Here, I got the "project charter" page first, which seems perfect. After that, I am unsure of the logic. There are blog posts (in an order I don't understand), but they are interrupted by the PEMM project page. 

Another thought: I tried searching for "PEMM" (https://test-web.cdh.princeton.edu/search/?q=PEMM). I did not get as many results as I did when I searched for "Princeton Ethiopian Miracles of Mary," even though those are the same thing (https://test-web.cdh.princeton.edu/search/?q=%22Princeton+Ethiopian+miracles+of+Mary%22). Is there a way to make all the "Princeton Ethiopian Miracles of Mary" results come up when a user searches for "PEMM"?  Saying this because it seems like abbreviations aren't unusual on CDH web (NLP, etc.).

**Comment by thatbudakguy** [comment]
thought I would post here to add to camey's testing above. Wagtail docs [claim that](https://docs.wagtail.io/en/stable/topics/search/indexing.html#signal-handlers):
> `wagtailsearch` provides some signal handlers which bind to the save/delete signals of all indexed models. This would automatically add and delete them from all backends you have registered in `WAGTAILSEARCH_BACKENDS`. These signal handlers are automatically registered when the `wagtail.search` app is loaded.

which would mean that the manual `update_index` management command is almost never necessary. i confirmed in QA by:
- running a search for "network" and observing that an event with "network" in the title was result #1 
- finding that event and removing the keyword "network" from the title, and publishing the change
- immediately running the same search, and observing that the event was no longer the top result

it may still be wise to run `update_index` as part of the deployment process, but I think for now we are good to do.

**Comment by thatbudakguy** [comment]
responding more directly to @cvansant's testing:

1. boosting (controlling which results appear before others) appears to [not be possible](https://docs.wagtail.io/en/stable/topics/search/searching.html#complex-search-queries) with the search backend we're using. so, unfortunately we can't rank certain fields (like whether you are an author vs. just mentioned) above or below others. this is a bit of a bummer, but somewhat to be expected since we're using a much simpler search engine than we normally do (e.g. for s&co or PPA).
2. you're totally right that all of the april 21 dates are the date of the migration, since that's the last change that happened to most of this content. we could get around this by instead using the _first_ published date, but i'm not sure what the implications for that would be... @rlskoeser thoughts? we could also try to detect if the last change was by a script or robot, but that seems a bit complicated.
3. the blog post chronological order is a bit strange, but i don't think we can control it. we can, though, at some point allow you to just sort all the results in reverse chronological order so that newest things come first. this would trade off with relevance ranking, but it would at least allow you to filter to only recent stuff if that's what you were interested in.
4. the issue of query substitution/expansion (PEMM -> Princeton Ethiopian...) is a good thought, but it doesn't look like the search backend supports that either. however, they do have a thing called [promoted search results](https://docs.wagtail.io/en/stable/editor_manual/administrator_tasks/promoted_search_results.html#promoted-search-results) where you can designate certain results to always appear first for a particular search. it's not quite the same, but it would let us ensure that the PEMM project page (for example) always comes up first whenever you search PEMM _or_ Princeton Ethiopian...etc. (and it would let us highlight that result if we want to, much like ads on google search). you can actually try it out right now in wagtail:

![Screen Shot 2021-08-17 at 12 09 59 PM](https://user-images.githubusercontent.com/4924494/129761953-a30da7f5-7e35-4a48-afb5-a3a109f1e540.png)

**Comment by rlskoeser** [comment]
>   you're totally right that all of the april 21 dates are the date of the migration, since that's the last change that happened to most of this content. we could get around this by instead using the _first_ published date, but i'm not sure what the implications for that would be... @rlskoeser thoughts? we could also try to detect if the last change was by a script or robot, but that seems a bit complicated.

I don't think first publication date is a good idea for content pages  — most of them are probably pretty old, and I don't want anyone removing and recreating them to try to get around this. It might be more meaningful for blog posts or other specific kinds of content, but not sure it's worth differentiating them.

Agree, it's not worth the effort to ignore modification dates based on scripted changes.

I suspect having all the dates based on the migration effect is a kind of temporary artifact that will fade: as we update and add content it will become less obvious and less important.

If not, we can always revisit in a later round of design & improvement. for search results

**Comment by rlskoeser** [comment]
>  the issue of query substitution/expansion (PEMM -> Princeton Ethiopian...) is a good thought, but it doesn't look like the search backend supports that either.  [...]

I did a little bit of looking at the wagtail search docs you linked, and it seems that postrges _does_ support defining synonyms, but it's not quite clear to me how or if you can manage them from wagtail (I think maybe they go in the database, which makes sense). I think synonyms should be out of scope for this first implementation, but we should think about adding them later (whether figuring out how to do it in postgres or implementing a solr search backend if we think it's merited).

**Comment by thatbudakguy** [comment]
> I don't think first publication date is a good idea for content pages  — most of them are probably pretty old, and I don't want anyone removing and recreating them to try to get around this. It might be more meaningful for blog posts or other specific kinds of content, but not sure it's worth differentiating them.

good point. one other idea i had was a quick management command or script that looks through all the pages, and if `last_published_at` is equal to the timestamp of the migration, sets it to the timestamp of the log entry immediately before the migration instead.

**Comment by rlskoeser** [comment]
@thatbudakguy is `last_published_at` used for anything else? I didn't know you could set it / override it like that. I would be concerned about it impacting something else that we don't want it to. if that's the date we use for last modified headers and modification time in the sitemap, then we shouldn't mess with it. 

If it's enough of a concern, it almost seems better to not display a modification date at all than monkey with trying to figure out how to get a more "meaningful" one.

**Comment by thatbudakguy** [comment]
it is used for the last modified headers, yeah — but it gets reset whenever you publish again, so it's not like the change would be permanent. if someone came along and edited the page, the timestamp would get updated to that point.

the reason this problem is occurring is because we set `first_published_at` during the exodus, but neglected to do `last_published_at` too (my fault), so this would basically just be correcting that.

**Comment by thatbudakguy** [comment]
@cvansant could you test this one final time now that #359 is also delivered and confirm that there were no regressions in functionality? I think it's good enough for a first pass, and we can revisit all these concerns during the next roadmap.

**Comment by cvansant** [comment]
Interesting the most common date is now April 13, rather than April 21!
